### ISSUE TITLE
Shengyi CMT03 Motor and LD-LS11-F  Controller?

### ISSUE THREAD

**Issue by spooknik** [EBiCS/EBiCS_Firmware#11]
Hello, 

I have a SCO e-Trekking Premium (Danish brand) and It has a Shengyi CMT03 motor installed. I believe it has a LD-LS11-F controller in it, but I am not totally sure. I cannot find any info on this controller inside the motor. 

I noticed the official USB Stick FPS2 connects via TX and RX pins which I have via the display cable. I assume this is for use with Lishui tools like SJW32 and their flasher.

This project's instruction connect via the SWDIO and SWCLK using an STlink for a connection to the STM32 chip on the controller. Is there a difference between these two? I cannot really find a SWDIO and SWCLK connector for my bike. Do I need to open up the motor and make connections via the pins there? Or can I buy a USB Stick FPS2 for connection via TX/RX

 I have made a [post ](https://endless-sphere.com/forums/viewtopic.php?f=2&t=118052)on Endless Sphere if you care to have a look. 

Thanks for the project and the help 👍 

EDIT: I took the motor apart and there is no sign of the mentioned controller. I am pretty sure this is not a Lishui controller on this motor, my mistake. Feel free to close this issue if you feel it's no relevant. 

EDIT2: I found the controller, it was much smaller than I expected, I depotted it and got to the PCB. The model number is LSW06-SY3CFSB. It uses the same STM32 chip and has debug ports on the top of the PCB. 
![IMG_1265](https://user-images.githubusercontent.com/40317809/196523444-c01fb73a-13c1-4266-9de5-3953d0ab0ff1.JPEG)
![IMG_1266](https://user-images.githubusercontent.com/40317809/196523450-a55dc616-b7df-462f-bff5-0b5dff5e38cc.JPEG)
![IMG_1268](https://user-images.githubusercontent.com/40317809/196523453-ecd60b2a-1fe2-4eb5-bd78-9fecbe85cbf2.JPEG)

**Comment by stancecoke** [comment]
yes, the OSF should work with this controller.
