### ISSUE TITLE
not compiling with Flash configurator

### ISSUE THREAD

**Issue by energizer77** [EBiCS/EBiCS_Firmware#2]
Hi @stancecoke, on the EBiCS branch, I changed following files to be able to compile :
- make/objects.list (line 21)
`"Src/eeprom.o"`

- make/subdir_src.mk
line 12
`../Src/eeprom.c \`
line 24
`./Src/eeprom.o \`
line 36
`./Src/eeprom.d \`

Also the configurator seems to remove some config.h lines like the EBICs display.

**Comment by stancecoke** [comment]
solved with commit https://github.com/EBiCS/EBiCS_Firmware/commit/fd96e1f172c7ba00f31401f974c6d795e1d3257c
