### ISSUE TITLE
Autodetect broken

### ISSUE THREAD

**Issue by erik-smit** [EBiCS/EBiCS_Firmware#26]
Autodetect is currently broken on master for me.
It seems to move one tick and then hang, just pushing current through the motor, but the motor remains rock solid and unmovable.
Suspecting the watchdog, I reverted to b4ccd57 and here it still works.

**Comment by stancecoke** [comment]
Hm, autodetect works for me. what kind of motor do you use?

**Comment by stancecoke** [comment]
Fixed it!
